AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - bin/*
    - db/schema.rb
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "db/migrate/*"
    - "spec/**/*"

Metrics/ClassLength:
  Exclude:
    - "spec/**/*"

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 20
  Exclude:
    - "db/migrate/*"
    - "spec/**/*"

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
