language: ruby
cache:
  bundler: true
  directories:
    - /home/travis/.rvm/
    - node_modules
rvm:
  - 2.5.2
services:
  - postgresql
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -yqq nodejs
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - bundle install -j $(nproc) --path vendor/bundle
  - bundle exec rubocop
  - RAILS_ENV=test bundle exec rake db:schema:load --trace
  - RAILS_ENV=test bundle exec rails db:migrate
  - RAILS_ENV=test bundle exec rails db:seed
  - RAILS_ENV=test bundle exec rspec
